print('Pizza Time!')
print(' ')
print('\t %s \t %s \t %s \t %s' % ('Size', 'No Toppings', 'One Topping', 'Two Toppings'))
print('\t %s \t %s \t %s \t %s' % ('----', '-----------', '-----------', '------------'))
print('\t %s \t $%4.2f \t\t $%.2f \t\t $%.2f' % ('Small', 6.95, 7.95, 8.95))
print('\t %s  $%.2f \t $%5.2f \t $%5.2f' % ('Medium', 10.75, 11.95, 12.25))
print('\t %s \t $%4s \t $%.2f \t $%.2f' % ('Large', 14.95, 15.95, 16.25))
print(' ')
print('Toppings')
print('--------')
print('\t %s \t %7s \t %s'  % ('Pepperoni', 'Garlic', 'Mushrooms'))
print('\t %s %16s \t %s' % ('Salami', 'Chorizo', 'Pineapple'))
print('\t %s %13s \t %s' % ('Jalapenos', 'Sausage', 'Ham'))